name: controle_financeiro
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^3.6.0
  custom_sliding_segmented_control: ^1.8.3
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.1
  flutter_signin_button: ^2.0.0
  table_calendar: ^3.1.1
  cloud_firestore: ^5.0.0
  uuid: ^4.4.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets: 
    - assets/image/
  uses-material-design: true

  