// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUbt9aDU37utq7Uuobq4JxEXJRbSGERGQ',
    appId: '1:79858515870:web:49186895ee83d6e1c2208f',
    messagingSenderId: '79858515870',
    projectId: 'economi-9e141',
    authDomain: 'economi-9e141.firebaseapp.com',
    storageBucket: 'economi-9e141.appspot.com',
    measurementId: 'G-R6V6K2PL56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsjype5QIQmCl76aeS2llETW4SlMsxvhs',
    appId: '1:79858515870:android:8d419db654ee5335c2208f',
    messagingSenderId: '79858515870',
    projectId: 'economi-9e141',
    storageBucket: 'economi-9e141.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv4qRo1T2afwNgw6V4PDU5NRGwXHWmTc0',
    appId: '1:79858515870:ios:17b18dab2bf48042c2208f',
    messagingSenderId: '79858515870',
    projectId: 'economi-9e141',
    storageBucket: 'economi-9e141.appspot.com',
    iosClientId: '79858515870-b524l5crrghv2u9ujqsg2631csoabm7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.controleFinanceiro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv4qRo1T2afwNgw6V4PDU5NRGwXHWmTc0',
    appId: '1:79858515870:ios:17b18dab2bf48042c2208f',
    messagingSenderId: '79858515870',
    projectId: 'economi-9e141',
    storageBucket: 'economi-9e141.appspot.com',
    iosClientId: '79858515870-b524l5crrghv2u9ujqsg2631csoabm7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.controleFinanceiro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUbt9aDU37utq7Uuobq4JxEXJRbSGERGQ',
    appId: '1:79858515870:web:12907c3923d6de12c2208f',
    messagingSenderId: '79858515870',
    projectId: 'economi-9e141',
    authDomain: 'economi-9e141.firebaseapp.com',
    storageBucket: 'economi-9e141.appspot.com',
    measurementId: 'G-C485D7BTRW',
  );

}